server:
  port: 8501
  context-path: /auth
security:
  basic:
    enabled: false
spring:
  application:
    name: auth-server
  datasource:
    url: jdbc:postgresql://ec2-54-247-123-231.eu-west-1.compute.amazonaws.com:5432/d74oqr268mfr3h?sslmode=require&amp;sslfactory=org.postgresql.ssl.NonValidatingFactory
    username: fuvfjacrliffjo
    password: c230d78c7c4b302a04ed76170de99164003331ffddc4542be518c9e8b8073321
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  