server:
  port: 8501
  context-path: /auth
  
security:
  basic:
    enabled: false
    
    
    
spring:
  application:
    name: auth-server
  datasource:
   #datasource:
    #url: jdbc:mysql://localhost:3306/notewitch?useSSL=false&useUnicode=yes&characterEncoding=UTF-8
    #username: root  
    #password: root
    #driver-class-name: com.mysql.jdbc.Driver
    #driver-class-name:  org.postgresql.Driver
    url: jdbc:postgresql:// + ${HEROKU_POSTGRESQL_MAROO_URL} + /d74oqr268mfr3h?useSSL=true
    username: ${HEROKU_POSTGRESQL_MAROON_USERNAME}  
    password: ${HEROKU_POSTGRESQL_MAROON_PASSWORD}
  jpa:
    show-sql: true 
    hibernate:
      ddl-auto: none
  thymeleaf:
    cache: false
 
 